main: ./dist

components: ./src/assets/components

styles:
  main: ./dist/assets/styles
  views: ./dist/assets/styles/views

scripts:
  main: ./dist/assets/scripts
  views: ./dist/assets/scripts/views

fonts:
  webfonts: ./dist/assets/fonts/webfonts
  iconfonts: ./dist/assets/fonts/iconfonts
