main: ./src

styles:
  main: ./src/assets/styles/main.sass
  views: ./src/assets/styles/views

scripts:
  main: ./src/assets/scripts/main.js
  views: ./src/assets/scripts/views

icons: ./src/assets/icons/**/**/**/**/**/*.svg

fonts:
  webfonts: ./src/assets/fonts/webfonts
  iconfonts: ./src/assets/fonts/iconfonts

data:
  main: ./config/template.yml
  boiler: ./config/template.boiler.yml
  views: ./src/assets/data
